### ISSUE TITLE
configuration file

### ISSUE THREAD

**Issue by el3ctron** [onozaty/firefox-shortcutkey2url#10]
i got a lot of links to add, and i am thinking in adding manually, where can i get the shorcut configuration file to edit it?? or to export it to another machine?? thanks!

**Comment by onozaty** [comment]
I'm sorry. There is no configuration file.
I would like to implement export and import functions in the near future.

Thanks.

**Comment by nelfs75gb** [comment]
please, create option to export/import sites allowing to copy config to a new computer.

**Comment by onozaty** [comment]
I will implement it.

**Comment by onozaty** [comment]
Implemented in version 4.2.0.
Please try to update.
