### ISSUE TITLE
Interactive filter for the URL list

### ISSUE THREAD

**Issue by iegorka** [onozaty/firefox-shortcutkey2url#14]
Hi,

Thank you for this very useful extension.

I'll like to ask you to see if it's possible to set interactive filter when the list is opened and there are some multi-letter ?

For example, with this configuration when I press the main "hotkey" I can see all items, but then if I type G I will see just two items (GS & GM) (or set some highlights for this two items) : 

```
const DEFAULT_SHORTCUTKEYS = [
  {key: 'GS', title: 'Google', action: ActionId.OEPN_URL_NEW_TAB, url: 'https://www.google.com/'},
  {key: 'GM', title: 'Gmail', action: ActionId.JUMP_URL, url: 'https://mail.google.com/'},
  {key: 'T', title: 'Twitter', action: ActionId.JUMP_URL, url: 'https://twitter.com/'},
  {key: 'F', title: 'Facebook', action: ActionId.JUMP_URL, url: 'https://www.facebook.com/'},
  {key: 'Y', title: 'YouTube', action: ActionId.JUMP_URL, url: 'https://www.youtube.com/'}
];
```

It will be very practical if the configuration contains many items with multi-letter.

Thank in advance.

**Comment by onozaty** [comment]
Thank you for the suggestion.
I would like to consider the implementation.

Thanks

**Comment by onozaty** [comment]
#15

**Comment by onozaty** [comment]
Hi @iegorka 

Supported in version 4.3.1.

If you check `Interactive filter of shortcut keys on the popup` of `Option`, you can interactively narrow down the shortcuts displayed in the popup.

Thanks.
