### ISSUE TITLE
Popup List does not appear

### ISSUE THREAD

**Issue by nelfs75gb** [onozaty/firefox-shortcutkey2url#18]
When the browser screen is less than 800 pixels and has at least 20 sites on the list:

After  pressed shortcut key defined in "Startup key" : Popup list does not appear.

But if the screen is maximized, the list appears.

**Comment by onozaty** [comment]
Hi @nelfs75gb 

It seems that if the browser width is reduced until the icon is no longer visible, the popup cannot be served.

![image](https://user-images.githubusercontent.com/47337/111025909-9cdaa600-842a-11eb-8472-122121f728ac.png)

![image](https://user-images.githubusercontent.com/47337/111025913-a6640e00-842a-11eb-8f82-afcb862e9243.png)

It seems to be a Firefox problem.

* https://bugzilla.mozilla.org/show_bug.cgi?id=1416414

You may be able to work around this by moving it to a position where it is always visible through customization.

![image](https://user-images.githubusercontent.com/47337/111026119-f98a9080-842b-11eb-8ec7-52572582e9e4.png)

Thanks.

**Comment by nelfs75gb** [comment]
It seems to be true.
I left the icon at the beginning of the bar and then yes, it worked.
Thanks.
