### ISSUE TITLE
Shortcut not working as expected, missing period

### ISSUE THREAD

**Issue by bit-man** [onozaty/firefox-shortcutkey2url#19]
Using Ctrl+.+T does not goes to Twitter URL, instead it opens a new tab meaning that period is not detected . The same happens for the remaining shortcuts

- Plugin: 4.3.1
- OS: LMDE 5 Elsie (Linux Mint Debian Edition)
- Browser : Firefox 99.0.1 (64-bit)

**Comment by onozaty** [comment]
Do you mean that the pop-up by the startup key does not appear?
![image](https://user-images.githubusercontent.com/47337/164977548-ef446165-fb58-42ea-bf0d-bf3bee28aacb.png)

If so, could you please try and change the startup key?

Thanks.

**Comment by bit-man** [comment]
I mean the enabled shortcuts does not work, instead the shortcuts with no period are being executed (pressing Ctrl+period+T creates new tab instead opening Twitter tab)
yes, changed the startup key but still not working :cry:

**Comment by onozaty** [comment]
After pressing the startup key, it is not necessary to keep the Ctrl key pressed.

Try pressing the Startup key and after the popup appears, press `T` as is. 
`Ctrl+period` -> `T` 

Thanks.

**Comment by bit-man** [comment]
Now it's working right
Thanks!
