### ISSUE TITLE
Option to open url in private mode

### ISSUE THREAD

**Issue by nelsonflaviosantos** [onozaty/firefox-shortcutkey2url#20]
If possible, 
Please create option to open url in private mode in firefox.

**Comment by onozaty** [comment]
Thanks for the suggestion.
I will consider it.

**Comment by onozaty** [comment]
Hi @nelsonflaviosantos 

Supported in v4.4.0.
To enable the Open Private Window actions, go to Extension Details and set "Run in Private Window" to "Allow".

Thanks.
