### ISSUE TITLE
The "script" form field disappears and won't come back with certain interations in the Options Page.

### ISSUE THREAD

**Issue by pbarney** [onozaty/firefox-shortcutkey2url#22]
**Summary of problem:** If you select `Open url in incognito window` or `Open current tab in incognito window`, the `Script` field disappears and does not come back when you switch to a different `Action`.

**Steps to reproduce:**

1. **Go to options page:**
  ![1](https://user-images.githubusercontent.com/428178/228298495-8dafc71a-36e5-476a-8d07-33d18175b2e5.png)

2. **Click `Add`.** Notice that we have five fields: `Key`, `Action`, `Title`, `URL`, `Script`:
  ![2](https://user-images.githubusercontent.com/428178/228298625-bdd1ca6a-e263-4030-8a26-e6820c670e39.png)

3. **Click on the `Action` dropdown and press the "down" key multiple times to scroll through all the options.** Notice that with each change of the Action dropdown, the number of fields changes. When we finally land on `Open current tab in incognito window`, we now have three fields: `Key`, `Action`, `Title`:
  ![3](https://user-images.githubusercontent.com/428178/228299020-6ee9b9b3-81a1-40d8-8ce4-f560e92b601b.png)
  
4. **Now select `Execute Script` from the dropdown.** Notice that we no longer have a `Script` field. There is no way to get the script field back.
  ![4](https://user-images.githubusercontent.com/428178/228299097-f8a392d9-8cbf-49e7-832d-ca2ee5b7594d.png)

**Comment by onozaty** [comment]
Thanks for the Issue.
I too have confirmed the bug.

**Comment by onozaty** [comment]
Fixed in v4.4.1.

Thanks.
