### ISSUE TITLE
Suggestion: Rename "Incognito Window" to "Private Window" for clarity.

### ISSUE THREAD

**Issue by pbarney** [onozaty/firefox-shortcutkey2url#23]
In Firefox, a private window is not called "Incognito Window." Firefox calls such windows "Private Windows." Chrome users may be familiar with the term "Incognito Window," but users who are only familiar with Firefox will not know that term.

**Comment by onozaty** [comment]
The code is the same as the Chrome version, hence the name.
I would like to consider whether to change the name, as there are advantages to keeping the code the same.

Thanks.

**Comment by pbarney** [comment]
In that case, I don't think it's significant enough to warrant changing the code. Feel free to close.

**Comment by onozaty** [comment]
> In that case, I don't think it's significant enough to warrant changing the code. Feel free to close.

Thanks.
