### ISSUE TITLE
Feature request: could you allow using Control + Space as add-on "start" combination

### ISSUE THREAD

**Issue by bybor** [onozaty/firefox-shortcutkey2url#4]
May be it could be hardcoded/displayed as "<space>" in UI, but any way to set it as value would be great.

**Comment by onozaty** [comment]
Hi @bybor 

You can set it by input "space".

![image](https://user-images.githubusercontent.com/47337/42135287-eb30731c-7d83-11e8-9cd7-9f58c9bd8228.png)

The input method will be improved in the future.

Thanks

**Comment by bybor** [comment]
Thanks!
