### ISSUE TITLE
Box showing in very ugly dark colors at any theme

### ISSUE THREAD

**Issue by onozaty** [onozaty/firefox-shortcutkey2url#6]
* https://addons.mozilla.org/ja/firefox/addon/shortcutkey2url/reviews/1223677/

It is necessary to be able to display beautifully in each theme.

**Comment by onozaty** [comment]
I want actual screen capture.

**Comment by theLittlePrinceAD** [comment]
Thank you for your response. Please find attached the screenshots - as with the original Dark and Light FF Quantum themes.

![dark theme](https://user-images.githubusercontent.com/44745082/47963301-f482ce80-e032-11e8-8de2-a0a3b4a91073.png)
![light theme](https://user-images.githubusercontent.com/44745082/47963302-f51b6500-e032-11e8-971e-0e38db5712c6.png)

**Comment by onozaty** [comment]
Hi @theLittlePrinceAD 

Thank you for screen capture.
I understood the content of the problem, so I will fix it.

**Comment by onozaty** [comment]
Hi @theLittlePrinceAD

It did not reproduce.

![image](https://user-images.githubusercontent.com/47337/48427513-3a1a6680-e7ac-11e8-9374-ea3898593a3a.png)

![image](https://user-images.githubusercontent.com/47337/48427657-92e9ff00-e7ac-11e8-8a0a-480c4cc078f7.png)

Do you have any other information?

**Comment by theLittlePrinceAD** [comment]
I would be happy to provide any info you may need in order to solve the problem.

**Comment by onozaty** [comment]
I'm sorry, but could you provide the following information?

* Firefox version
* OS type

Also, because there is a possibility that it may be influenced by other extended functions, can you check other than ShortcutKey2URL by invalidating it?

Thanks

**Comment by theLittlePrinceAD** [comment]
I am sorry for being late with my answer, had a business trip.

After disabling ALL add-ons except ShortcutKEY2URL the colors in its window remain the same as reported.
FF - 63.03.
OS - Win 10 Enterprise, 1803 build 17134.407.

**Comment by onozaty** [comment]
Thank you for the information.

Since I tried to fix it, would you please try unpacking the following files as a test and loading from the add-on debug?

* [firefox-shortcutkey2url-6.zip](https://github.com/onozaty/firefox-shortcutkey2url/files/2595823/firefox-shortcutkey2url-6.zip)

Please disable installed Shortcutkey2URL once and install it with reference to the following procedure.
* [Temporary installation in Firefox \- Mozilla \| MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Temporary_Installation_in_Firefox)

**Comment by theLittlePrinceAD** [comment]
1) Downloaded your ZIP and unpacked.
2) Disabled the add-on ShortcutKEY2URL (all others are enabled)
3) "about:debugging" - "Load Temporary Add-on" - open the extension's directory and select actions.js.
4) add-on active. Working as expected (black text on white background).

**Comment by onozaty** [comment]
Thank you for confirmation.
I am thinking to release it with this, please wait a little more.

**Comment by theLittlePrinceAD** [comment]
I am glad things are positive!
Wish you success!
P.S. After your update will edit my comment in FF's add-on site.

**Comment by onozaty** [comment]
Hi @theLittlePrinceAD 

It was released as 4.0.2.
Please try it.

Thank you for cooperation!

**Comment by theLittlePrinceAD** [comment]
Hi,
Everything working as expected!
Thank you for quick and professional support!
Review updated :)
Best regards.
