### ISSUE TITLE
not executing scripts

### ISSUE THREAD

**Issue by el3ctron** [onozaty/firefox-shortcutkey2url#9]
i am trying to execute a bookmarllet on Mozilla Firefox 68.0.1 but nothing happens

1. i open ShortcutKey2URL config
2. i assign a key
3. on action i select "execute script"
4. i assign a title
5. on script field i add the code

the code is like this

javascript:(%20function(e){var%20t=document,s=window,n=s.getSelection,o=t.getSelection,i=t.selection,l=t.location,r=void%200;r=n?n():o?o():i?i.createRange().text:0;var%20a=e+"?url="+encodeURIComponent(l.href)+"&title="+encodeURIComponent(t.title)+"&text="+encodeURIComponent(r)+"&v=5",d=function(){s.open(a,"t","toolbar=0,resizable=1,scrollbars=1,status=1,width=660,height=570")||(l.href=a)};/Firefox/.test(navigator.userAgent)?setTimeout(d,0):d()}%20)(%20'https://wordpress.com/post/el3ctron.wordpress.com'%20)

but nothing happens, maybe shortcutkey2url dont support javascripts??

there is a way to execute that bookmarklet/code??

**Comment by onozaty** [comment]
In the case of `execute script`, enter the JavaScript code as it is.
Therefore, the input of javascript scheme becomes unnecessary.

Thanks.

**Comment by bybor** [comment]
@onozaty, thank you! Pocket's (getpocket.com) bookmarklet started working for me when I removed both "javascript:" and also "(function() {" and its closing part "})()" as well, leaving only the "body" of bookmarklet

**Comment by el3ctron** [comment]
@bybor i start to erase some code   but i think i am doing wrong, please can you write your pocket example, with original code and the "new" code?

my old bookmarklet: 

`javascript:(%20function(e){var%20t=document,s=window,n=s.getSelection,o=t.getSelection,i=t.selection,l=t.location,r=void%200;r=n?n():o?o():i?i.createRange().text:0;var%20a=e+"?url="+encodeURIComponent(l.href)+"&title="+encodeURIComponent(t.title)+"&text="+encodeURIComponent(r)+"&v=5",d=function(){s.open(a,"t","toolbar=0,resizable=1,scrollbars=1,status=1,width=660,height=570")||(l.href=a)};/Firefox/.test(navigator.userAgent)?setTimeout(d,0):d()}%20)(%20'https://wordpress.com/post/el3ctron.wordpress.com'%20)`



must be like: 

`var%20t=document,s=window,n=s.getSelection,o=t.getSelection,i=t.selection,l=t.location,r=void%200;r=n?n():o?o():i?i.createRange().text:0;var%20a=e+"?url="+encodeURIComponent(l.href)+"&title="+encodeURIComponent(t.title)+"&text="+encodeURIComponent(r)+"&v=5",d=function(){s.open(a,"t","toolbar=0,resizable=1,scrollbars=1,status=1,width=660,height=570")||(l.href=a)};/Firefox/.test(navigator.userAgent)?setTimeout(d,0):d()`

(i use this last code and do not work :( )

**Comment by onozaty** [comment]
@el3ctron 
Try replacing `%20` with a space.

```javascript
( function(e){var t=document,s=window,n=s.getSelection,o=t.getSelection,i=t.selection,l=t.location,r=void 0;r=n?n():o?o():i?i.createRange().text:0;var a=e+"?url="+encodeURIComponent(l.href)+"&title="+encodeURIComponent(t.title)+"&text="+encodeURIComponent(r)+"&v=5",d=function(){s.open(a,"t","toolbar=0,resizable=1,scrollbars=1,status=1,width=660,height=570")||(l.href=a)};/Firefox/.test(navigator.userAgent)?setTimeout(d,0):d()} )( 'https://wordpress.com/post/el3ctron.wordpress.com' )
```

Thanks.

**Comment by bybor** [comment]
I think it should be something like this
`var t=document,s=window,n=s.getSelection,o=t.getSelection,i=t.selection,l=t.location,r=void 0;r=n?n():o?o():i?i.createRange().text:0;var a="https://wordpress.com/post/el3ctron.wordpress.com"+"?url="+encodeURIComponent(l.href)+"&title="+encodeURIComponent(t.title)+"&text="+encodeURIComponent(r)+"&v=5",d=function(){s.open(a,"t","toolbar=0,resizable=1,scrollbars=1,status=1,width=660,height=570")||(l.href=a)};/Firefox/.test(navigator.userAgent)?setTimeout(d,0):d();
`
Here I removed `( function(e) {` part, and also the closing part of function definition, but to keep it working I moved `url` (or `e`) parameter into the body of javascript. I don't know what this bookmarklet does, but I think it gets executed.

I removed `( function (e) {` and the closing part because I did the same for my Pocket bookmarklet, or it didn't work the other way.

**Comment by onozaty** [comment]
Hi @el3ctron @bybor 

Now that you can write the script in the javascript scheme, can you try it?
Released in version 4.1.0.

**Comment by el3ctron** [comment]
i have good news and a bad one:

the good ones is that is working with almost all of my bookmarklets :) thanks!!

the bad one is that wordpress bookmarklet still not working :(

when i press the wordpress bookmarklet button on toolbar it works, (so the bookmarklet is working), but when i invoke it in shortcutkey2url dont run

i replace the %20 for spaces like this

`javascript:( function(e){var t=document,s=window,n=s.getSelection,o=t.getSelection,i=t.selection,l=t.location,r=void 0;r=n?n():o?o():i?i.createRange().text:0;var a=e+"?url="+encodeURIComponent(l.href)+"&title="+encodeURIComponent(t.title)+"&text="+encodeURIComponent(r)+"&v=5",d=function(){s.open(a,"t","toolbar=0,resizable=1,scrollbars=1,status=1,width=660,height=570")||(l.href=a)};/Firefox/.test(navigator.userAgent)?setTimeout(d,0):d()} )( 'https://wordpress.com/post/el3ctron.wordpress.com' )`

and try with the original one (with %20) but dont run.

**Comment by el3ctron** [comment]
this one dont run too : 

`javascript:var%20d=document,w=window,e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='http://www.tumblr.com/share',l=d.location,e=encodeURIComponent,p='?v=3&u='+e(l.href)%20+'&t='+e(d.title)%20+'&s='+e(s),u=f+p;try{if(!/^(.*\.)?tumblr[^.]*$/.test(l.host))throw(0);tstbklt();}catch(z){a%20=function(){if(!w.open(u,'t','toolbar=0,resizable=0,status=1,width=450,height=430'))l.href=u;};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else%20a();}void(0)`

**Comment by onozaty** [comment]
Hi @el3ctron 

There seems to be a problem with the reference method of `getSelection`.

It worked if I changed it as follows.

```
javascript:( function(e){var t=document,s=window,i=t.selection,l=t.location,r=void 0;r=s.getSelection?s.getSelection():t.getSelection?t.getSelection():i?i.createRange().text:0;var a=e+"?url="+encodeURIComponent(l.href)+"&title="+encodeURIComponent(t.title)+"&text="+encodeURIComponent(r)+"&v=5",d=function(){s.open(a,"t","toolbar=0,resizable=1,scrollbars=1,status=1,width=660,height=570")||(l.href=a)};/Firefox/.test(navigator.userAgent)?setTimeout(d,0):d()} )( 'https://wordpress.com/post/el3ctron.wordpress.com' )
```

**Comment by el3ctron** [comment]
thanks for your help @onozaty the new wordpress script now is working, thanks. I just want to ask you a final favor please, i know that this is not a error/bug from shorcutkey2url, and i am closing this issue, but is the only person who could help me, couse the tumblr one is the only bookmarklet that dont run, i replace the %20 for spaces and the original one is: 

`javascript:var d=document,w=window,e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='http://www.tumblr.com/share',l=d.location,e=encodeURIComponent,p='?v=3&u='+e(l.href) +'&t='+e(d.title) +'&s='+e(s),u=f+p;try{if(!/^(.*\.)?tumblr[^.]*$/.test(l.host))throw(0);tstbklt();}catch(z){a =function(){if(!w.open(u,'t','toolbar=0,resizable=0,status=1,width=450,height=430'))l.href=u;};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else a();}void(0)`

i replace with your changes on wordpress bookmarklet, like this (maybe i do a so funny code couse a i dont know javascript):

`javascript:var d=document,w=window,i=t.selection,l=t.location,r=void 0;r=s.getSelection?s.getSelection():t.getSelection?t.getSelection(),x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='http://www.tumblr.com/share',l=d.location,e=encodeURIComponent,p='?v=3&u='+e(l.href)%20+'&t='+e(d.title)%20+'&s='+e(s),u=f+p;try{if(!/^(.*\.)?tumblr[^.]*$/.test(l.host))throw(0);tstbklt();}catch(z){a%20=function(){if(!w.open(u,'t','toolbar=0,resizable=0,status=1,width=450,height=430'))l.href=u;};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else%20a();}void(0)`

but did not run ;( i will close this issue even if you could help me or not.

Thanks again.

**Comment by onozaty** [comment]
Hi @el3ctron 

It worked if I changed it as follows.


```javascript
javascript:var d=document,w=window,x=d.selection,s=(w.getSelection?w.getSelection():(d.getSelection)?d.getSelection():(x?x.createRange().text:0)),f='http://www.tumblr.com/share',l=d.location,e=encodeURIComponent,p='?v=3&u='+e(l.href) +'&t='+e(d.title) +'&s='+e(s),u=f+p;try{if(!/^(.*\.)?tumblr[^.]*$/.test(l.host))throw(0);tstbklt();}catch(z){a =function(){if(!w.open(u,'t','toolbar=0,resizable=0,status=1,width=450,height=430'))l.href=u;};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else a();}void(0)
```

**Comment by el3ctron** [comment]
thanks again !! now is working! i wonder what kind of scripts you use? maybe people could do a better use to this amazing firefox extension, thanks for your help!
